### ISSUE TITLE
Text mode: not working on CGA cards

### ISSUE THREAD

**Issue by jsmolina** [marco-sacchi/RLoader#34] opened 2022-10-29 17:01 UTC
**Describe the bug**
I would expect that textmode works on CGA mode, but it shows garbled screen intead. 

**To Reproduce**
1. Open any emulator (86box, pcem) or real PCXT.
2. execute rloader.
3. See error

**Expected behavior**
Garblet text is happening

**Screenshots**
<img width="634" alt="image" src="https://user-images.githubusercontent.com/447481/198843926-421a1104-2be4-4a8f-b76c-13ffb21c4962.png">

**Environment**
- Running on: any PCXT
- OS: any msdos version

**Additional context**

**Comment by marco-sacchi** [comment] 2022-10-29 18:04
Sorry, but I forgot to enter the RLoader version used in the bug report template.

What version are you using?
Do you have the same result with all versions?

**Comment by mills32** [comment] 2022-10-29 19:48
I tested this, it looks like pcem works well when using cga card. If you use tandy, it does not work well.

Dosbox x also fails, in CGA and tandy modes. 

Tandy text mode is the same as cga, it should work OK.

**Comment by marco-sacchi** [comment] 2022-10-30 11:44
Thanks @mills32 for testing. I was able to reproduce the problem with doxbox-x version 0.83.12.

@jsmolina, from your screenshot I was unable to guess what could have caused that display since I use the BIOS interrupt 0x10, avoiding direct access to the vram to maximize compatibility between systems and configurations, but checking with a populated list, I got an idea of what it should be.

Since among the data returned by the bios regarding the status of the current video mode there is no number of lines, I was forced to read it directly from the *Video Control Data Area 2* ram location (address 0040:0084). Probably the dosbox-x bios and those of some emulators and some real systems apparently do not return the correct value.

I'll check and update you, I need to make Borland C usable from dosbox-x to be able to test my guess. If confirmed I will have to find a safer way to retrieve the number of rows.

**Comment by marco-sacchi** [comment] 2022-10-30 12:06
I remembered that there is the `DEBUG` command in dosbox-x, and I was able to confirm what I had guessed:
```
                        +---- Number of Rows on the Screen (Minus 1), Byte
                        v
0040:0080  1E 00 3E 00 00 08 00 00-00 00 00 00 00 00 00 00 ..>.............
0040:0090  00 00 00 00 00 00 10 12-00 00 00 00 00 00 00 00 ................
0040:00A0  00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 ................
0040:00B0  00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 ................
0040:00C0  00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 ................
0040:00D0  00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 ................
0040:00E0  00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 ................
0040:00F0  00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 ................
```
As you can see at 0040:0084 there is a 00, instead it should be 24 (for 25 line text modes).

**Comment by marco-sacchi** [comment] 2022-10-30 16:18
@jsmolina, @mills32, from the tests done with dosbox-x now RLoader works correctly even on CGA mono and composite, tandy, pcjr, amstrad, mcga, mda machines.

![cga_mono](https://user-images.githubusercontent.com/81907055/198889491-6725bf83-fb59-4787-a807-0ab207664a95.png)
![tandy](https://user-images.githubusercontent.com/81907055/198889495-d63ee2e4-789a-4d55-b7e1-57f0a6eca42e.png)


Let me know if it solved also for the other emulators (downloading the release [1.0.4](https://github.com/marco-sacchi/RLoader/releases/tag/v1.0.4)) in order to close the issue .

**Comment by mills32** [comment] 2022-10-30 21:41
Thanks!.

I wanted to use this for a project, but maybe it is too big for me. Anyway it helped a lot, and also it is great that it is now working for cga, tandy and mda. 

About ascii "images" you are right, They will be slow for old pcs like 8088s, and it is difficult to generate them, even if they are simple logos or shapes.

**Comment by jsmolina** [comment] 2022-10-30 21:43
wow impressive!!! lot of thanks, should we close then this issue?

**Comment by jsmolina** [comment] 2022-10-30 21:45
@marco-sacchi not sure if you will find it useful, but I created an automatic list generator using python
https://github.com/jsmolina/simple-menu-dos-launcher/blob/main/rloadergen.py


Example usage:
python3 menugen.py -i /Users/jsmolina/DIST/GAMES1 -i /Users/jsmolina/DIST/GAMES2 -o /Users/jsmolina/OUT -d c:\\menu

it takes a list of directories with long names, and generates dos directories + LIST.txt automatically.

**Closed** 2022-10-31 11:10 UTC
Labels: bug

**Comment by marco-sacchi** [comment] 2022-10-31 12:18
@jsmolina, the list generator can be interesting, I'll be looking at it next weekend.

Please start a discussion next time, instead of adding a post to an open issue. I am the only maintainer and I have specifically activated the "Discussions" section to keep the list of issues clean, and to more easily reach users who want to propose new ideas and features.

If you can't start a discussion just let me know, I'll check the permissions.
